name: eShopOnWeb Build and Deploy

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-eshoponweb-westeurope
  LOCATION: westeurope
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 03625f30-897d-40c1-922e-dac326960070
  WEBAPP_NAME: devops-webapp-westeurope-143752838

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore all projects
        run: dotnet restore ./eShopOnWeb.sln

      - name: Build all projects
        run: dotnet build ./eShopOnWeb.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./eShopOnWeb.sln --configuration Release --no-build --verbosity normal

      - name: Publish Web App
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ./publish_output
          cd ./publish_output
          zip -r ../app.zip .

      - name: Upload Web App artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: app.zip

      - name: Upload Bicep template
        uses: actions/upload-artifact@v4
        with:
          name: bicep
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (Bicep)
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./artifacts/bicep/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      - name: Deploy Web App (ZIP)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          package: ./artifacts/webapp/app.zip
