<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="6.1.0" />
    <PackageReference Include="Ardalis.GuardClauses" Version="4.5.0" />
    <PackageReference Include="Ardalis.Result" Version="9.1.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorShared\BlazorShared.csproj" />
  </ItemGroup>

</Project>
