name: eShopOnWeb Build and Test

on: workflow_dispatch

env:
  RESOURCE-GROUP: rg-eshoponweb-westeurope
  LOCATION: westeurope
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 03625f30-897d-40c1-922e-dac326960070
  WEBAPP-NAME: devops-webapp-westeurope-143752838

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore ./eShopOnWeb.sln

      - name: Build
        run: dotnet build ./eShopOnWeb.sln --configuration Release --no-restore

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release --no-build
        continue-on-error: true   # ✅ Tests can fail without stopp
